wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 200
backbone:
  desc: null
  value: dino
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1736493802.049838
    t:
      1:
      - 1
      - 5
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      6: 4.31.0
      8:
      - 2
      - 5
      13: linux-x86_64
